### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by pertrai1**

### CODE REVIEW

**Comment by jkresner** [comment]
Ooooops @pertrai1my bad please don't merge into master ;)

**Comment by jkresner** [comment]
@pertrai1 can you take down your tweet, the repo is not a great place to send people to help. Better via the editor.

**Comment by pertrai1** [comment]
@jkresner Thank you. my bad on the merge. What do you mean about send people via editor?

**Comment by jkresner** [comment]
Using the forking and live editor feature on AirPair.com
ᐧ

On Wed, Mar 18, 2015 at 1:46 PM, Rob Simpson notifications@github.com
wrote:

> @jkresner https://github.com/jkresner Thank you. my bad on the merge.
> What do you mean about send people via editor?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/a-well-designed-api-approach/pull/1#issuecomment-83164502
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by pertrai1** [comment]
ok, will make sure that I use that

**Pull request merged**
